In [12]:
config = {
    "model_type": "skip-light",
    "input_shape": 4,
    "amplitude_shape": 36,
    "data_dir": "/scratch/akula.ha/dataset",
    "seed": 42,
    "var_y": [
        "y5",
        "y6"
    ],
    "activation": "leaky_relu",
    "width": 31,
    "depth": 10,
    "skip_block_layers": 5,
    "beta": 0,
    "alpha": 0,
    "normal_scaled": False,
    "lr_decay_type": "exp",
    "initial_lr": 0.003,
    "final_lr": 1e-06,
    "decay_steps": 120000,
    "train-sample-size": 10000000,
    "validate-sample-size": 500000,
    "test-sample-size": 500000,
    "use_MC_sample": False,
    "batch_size": 1024,
    "steps_per_epoch": 2400,
    "early_stopping_start_epoch": 50,
    "patience": 50,
    "monitor": "val_mse",
    "loss": "mse",
    "gradient_clipping": True,
    "verbose": 1,
    "base_directory": "../models/",
    "epochs": 2000,
    "model-uuid": "ef8e7636",
    "start_time": "2025-05-07 21:39:40 -0400",
    "device": "cuda",
    "directory": "../models/skip-light-torch-4D-y5_y6-ef8e7636",
    "train-samples-used": 6,
    "validate-samples-used": 6,
    "test-samples-used": 6,
    "n_targets": 2,
    "scaling": {},
    "trainable_parameters": 49819,
    "non_trainable_parameters": 0,
    "total_parameters": 49819,
    "final_decayed_lr": 4.4758200183300384e-05,
    "final_validation_r2": 99.74279299379268,
    "final_validation_loss": 0.026469253109972397,
    "last_epoch": 182,
    "n_training_epochs": 132,
    "fit_time": "2:05:48",
    "test_metrics": {
        "r2": {
            "y5": 59.34949379940995,
            "y6": 41.53556692441772,
            "model": 99.8367708984802
        },
        "abs_score": {
            "y5": 99.47024307869438,
            "y6": 99.65569012719476,
            "model": 97.01768156003165
        }
    },
    "end_time": "2025-05-07 23:47:09 -0400"
}

In [13]:
import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt
from pyspark.sql import SparkSession
from pyspark.sql import dataframe
from pyspark.sql.types import StructType, StructField, DoubleType
from sklearn import metrics
import time
import sys
import logging
import uuid
import os
import shutil
import json
import argparse
import pytorch_model_summary as pms

In [14]:
def init_torch(config):
    ''' function for initializing the seeds
        arguments:
            config: the configuration file
    '''
    gen = torch.manual_seed(config['seed'])
    torch.set_default_dtype(torch.float64)
    
    device = get_device()

    if device.type == 'cpu':
        torch.set_num_threads(64)
        # torch.set_num_interop_threads(1)

    logging.info(f' torch is using {device}')
    
    return device

In [15]:
def get_device():
    ''' function to get the device the NN is running on, CPU or GPU
    '''
    if torch.cuda.is_available():
        device = torch.device("cuda:0")
    else: 
        device = torch.device("cpu")
        
    return device

In [16]:
device = init_torch(config)

In [17]:
import re

In [18]:
def load_data(config):
    """ Load the data using pyspark
        arguments:
            config: the configuration file
        returns:
            df['train']: the training dataframe
            df['validate']: the validation data set
            df['test']: the testing data set
            spark: the spark session
    """
    
    # Spark session and configuration
    logging.info(' creating Spark session')
    spark = (SparkSession.builder.master("local[48]")
             .config('spark.executor.instances', 16)
             .config('spark.executor.cores', 16)
             .config('spark.executor.memory', '10g')
             .config('spark.driver.memory', '15g')
             .config('spark.memory.offHeap.enabled', True)
             .config('spark.memory.offHeap.size', '20g')
             .config('spark.dirver.maxResultSize', '20g')
             .config('spark.debug.maxToStringFields', 100)
             .appName("amp.hell").getOrCreate())

    # Enable Arrow-based columnar data 
    spark.conf.set("spark.sql.execution.arrow.pyspark.enabled", "true")
    spark.conf.set(
        "spark.sql.execution.arrow.pyspark.fallback.enabled", "true"
    )
    logging.info(' Spark initialized')
    
    # read the data into a spark frame
    start = time.time()
    path = config['data_dir']
    if path[-1] != '/':
        path = path + '/'
    input_var = ['x'+str(i+1) for i in range(config['input_shape'])]
    target_var = ['y'+str(i+1) for i in range(config['amplitude_shape'])]

    header = input_var + target_var
    schema = StructType([StructField(header[i], DoubleType(), True) for i in range(config['input_shape']+config['amplitude_shape'])])

    df = {}
    df['train'] = spark.read.options(delimiter=',').schema(schema).format("csv").load(path+'train/*.csv.*', header='true')
    
    
    if config['var_y'] == 'all': config['var_y'] = df['train'].columns[config['input_shape']:]
    
    
    if config['use_MC_sample']:
        mc_suffix = '_mc'
    else:
        mc_suffix = ''
    df['validate'] = spark.read.options(delimiter=',').schema(schema).format("csv").load(path+'validate'+mc_suffix+'/*.csv.*', header='true')
    df['test'] = spark.read.options(delimiter=',').schema(schema).format("csv").load(path+'test'+mc_suffix+'/*.csv.*', header='true')

    logging.info(' data loaded into Spark session in {:.3f} seconds'.format(time.time() - start))
    
    # transfer the data to a pandas dataframe
    start = time.time()
    train_sample = min(config['train-sample-size'], df['train'].count())
    validate_sample = min(config['validate-sample-size'], df['validate'].count())
    test_sample = min(config['test-sample-size'], df['test'].count())
    
    ########################################################################
    # Assuming config['var_y'] is the list
    operators = ['+', '-', '*', '/']

    # List of items with operators
    with_operator = [item for item in config['var_y'] if any(op in item for op in operators)]
    print(with_operator)
    # List of items without operators
    without_operator = [item for item in config['var_y'] if all(op not in item for op in operators)]
    print(without_operator)
    
    # Split the items with operators into individual components
    split_items = [subitem for item in with_operator for subitem in re.split(r'\+|\-|\*|\/', item)]

    # Combine the split items with the items without operators
    combined_list = without_operator + split_items

    # Remove duplicates to get a unique list
    unique_list = list(set(combined_list))

    # Sort the list if you want it in a specific order (optional)
    unique_list.sort()
    
    ########################################################################
    
    df['train'] = df['train'].select(*input_var, *unique_list).limit(train_sample).toPandas() 
    df['validate'] = df['validate'].select(*input_var, *unique_list).limit(validate_sample).toPandas()
    df['test'] = df['test'].select(*input_var, *unique_list).limit(test_sample).toPandas()
    
    # Step 1: Perform the operations
    for key in ['train', 'validate', 'test']:
        for expr in config['var_y']:
            if any(op in expr for op in ['+', '-', '*', '/']):
                # Split the expression into individual components and operator
                components = re.split(r'(\+|\-|\*|\/)', expr)

                # Evaluate the expression and create a new column
                if len(components) == 3:  # This should match the pattern "y1 + y3"
                    col1, operator, col2 = components

                    if operator == '+':
                        df[key][expr] = df[key][col1] + df[key][col2]
                    elif operator == '-':
                        df[key][expr] = df[key][col1] - df[key][col2]
                    elif operator == '*':
                        df[key][expr] = df[key][col1] * df[key][col2]
                    elif operator == '/':
                        df[key][expr] = df[key][col1] / df[key][col2]

    # Filter split_items to keep only those that are also in without_operator
    filtered_items = [item for item in split_items if item not in without_operator]

    # Drop the filtered items from the DataFrames
    for key in ['train', 'validate', 'test']:
        df[key] = df[key].drop(columns=filtered_items, errors='ignore')

    
    logging.info(' training data shape: {} x {}'.format(df['train'].shape[0], df['train'].shape[1]))
    logging.info(' validation data shape: {} x {}'.format(df['validate'].shape[0], df['validate'].shape[1]))
    logging.info(' testing data shape: {} x {}'.format(df['test'].shape[0], df['test'].shape[1]))
    
    config['train-samples-used'] = df['train'].shape[1]
    config['validate-samples-used'] = df['validate'].shape[1]
    config['test-samples-used'] = df['test'].shape[1]

    logging.info(' data loaded into pandas dataframe in {:.3f} seconds'.format(time.time() - start))
    
    logger = spark._jvm.org.apache.log4j
    logging.getLogger("py4j.clientserver").setLevel(logging.WARN)

    return df, spark

In [20]:
df, spark = load_data(config)

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/05/08 15:36:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

[]
['y5', 'y6']

In [21]:
df

{'train':                    x1        x2        x3        x4          y5          y6
 0        5.308962e-08  0.309913  0.050721  0.629043  119.890134 -131.188649
 1        3.505005e-07  0.281701  0.997791  0.482102  -11.651600   15.257625
 2        4.480013e-07  0.609822  0.147178  0.852029  227.064607 -242.366660
 3        6.298025e-07  0.258704  0.408208  0.122103  -27.431008   31.266244
 4        1.014703e-06  0.417312  0.940159  0.743944  111.235489 -114.351289
 ...               ...       ...       ...       ...         ...         ...
 3393721  9.937817e-01  0.520471  0.116823  0.381197   -3.462783   -0.628595
 3393722  9.970094e-01  0.248280  0.539416  0.161634   -5.912596    0.031616
 3393723  9.974963e-01  0.255944  0.522281  0.471605   -7.472055   -0.181993
 3393724  9.976171e-01  0.892835  0.290839  0.270442   -3.183277   -1.728482
 3393725  9.990412e-01  0.747992  0.462169  0.535807   -3.356216   -1.160603

 [3393726 rows x 6 columns],
 'validate':                   x1        x2        x3        x4          y5          y6
 0       5.354692e-07  0.300617  0.526366  0.059579   -8.184049   12.836841
 1       9.024278e-07  0.899253  0.434876  0.475627   82.753550  -85.655862
 2       1.509448e-06  0.827457  0.111961  0.383265  135.201585 -141.116059
 3       2.818238e-06  0.026469  0.460243  0.243116 -307.910481  321.571892
 4       3.436705e-06  0.073680  0.266952  0.102322 -234.340750  245.224692
 ...              ...       ...       ...       ...         ...         ...
 499995  2.508851e-01  0.381725  0.381386  0.696382  -15.352854   -4.878300
 499996  2.509296e-01  0.177722  0.616678  0.067511  -22.578762   -1.033192
 499997  2.513854e-01  0.961017  0.028367  0.942905  -14.607838  -33.053308
 499998  2.516266e-01  0.753230  0.433952  0.703720  -10.080715   -7.518504
 499999  2.521219e-01  0.400000  0.793942  0.387747  -12.021422   -3.451030

 [500000 rows x 6 columns],
 'test':                   x1        x2        x3        x4          y5          y6
 0       5.434361e-07  0.147431  0.774351  0.245984 -174.455943  186.963621
 1       2.254383e-06  0.705441  0.511854  0.034134  152.387746 -158.078358
 2       3.135050e-06  0.348233  0.460954  0.283262   63.641536  -64.647520
 3       3.604113e-06  0.659904  0.123490  0.852356  223.437810 -239.135900
 4       3.774481e-06  0.547915  0.649524  0.693039  171.113443 -177.570199
 ...              ...       ...       ...       ...         ...         ...
 499995  4.796587e-01  0.902703  0.699405  0.882771   -8.360206   -8.187200
 499996  4.803526e-01  0.952353  0.139955  0.355823   -7.330009   -8.443630
 499997  4.804764e-01  0.230907  0.985840  0.120947  -10.881412   -0.363873
 499998  4.811125e-01  0.888229  0.691187  0.302232   -5.679233   -4.133330
 499999  4.812678e-01  0.239973  0.513227  0.599417  -15.277579   -1.359047

 [500000 rows x 6 columns]}

In [22]:
def build_data_loaders(df, config):
    ''' function to build the data loaders
        arguments:
            df: dictionary of pandas dataframe for test, validation, and train
            config: configuration file
        returns:
            train_loader: the training set loader
            validation_loader: the validation set loader
            test_loader: the test set loader
    '''
    
    # slice and dice the data into train, validation and test sets
    df_test_data =  df['test']
    df_validation_data = df['validate']
    df_train_data = df['train']

    test_data = df_to_tensor(df_test_data, config)
    validation_data = df_to_tensor(df_validation_data, config)
    train_data = df_to_tensor(df_train_data, config)

    # load the data into torch tensor batches
    batch = config["batch_size"]
    numworkers = 2 if get_device().type == 'cpu' else 0
    train_loader = torch.utils.data.DataLoader(train_data, batch_size=batch, shuffle=True, num_workers=numworkers, drop_last=True)
    validation_loader = torch.utils.data.DataLoader(validation_data, batch_size=batch, shuffle=True, num_workers=numworkers, drop_last=True)
    test_loader = torch.utils.data.DataLoader(test_data, batch_size=batch, shuffle=False, num_workers=numworkers, drop_last=True)
    
    return train_loader, validation_loader, test_loader

In [36]:
len(train_loader)

NameError: name 'train_loader' is not defined

In [37]:

class df_to_tensor(torch.utils.data.Dataset):
    ''' class to convert dataframe to torch tensor
    '''
 
    def __init__(self, df, config):
        self.df = df.copy(deep = True)
        
        # extract x and scale
        x = df.iloc[:, :config['input_shape']]
        df['x1'] = df['x1'].apply(lambda x: x_scale(x))
        
        # extract y
        # if config['var_y'] == 'all':
        #     y = df.iloc[:, config['input_shape']:]
        # else:
        y = df[config['var_y']]
        
        # number of targets
        config['n_targets'] = y.shape[1]
            
        # scale y
        config['scaling'] = {}
        for column in y.columns:
            y[column] = y[column].apply(lambda y: y_scale(y))
            if config['normal_scaled']:
                y[column] = normalize(y, config, column)

        # put them in tensors. Note: the reshaping of y.
        self.x = torch.tensor(x.values, dtype=torch.float64).to(get_device())
        self.y = torch.tensor(y.values, dtype=torch.float64).reshape(-1, config['n_targets']).to(get_device())
 
    def __len__(self):
        return len(self.x)
   
    def __getitem__(self,idx):
        return self.x[idx], self.y[idx]

In [38]:
def normalize(df, config, var_y):
    """ a function to normaliza the target distribution
        arguments:
            df: dataframe containing the target variable
            config: the config file with the run configuration
            var_y: the variable to be normalized
    """
    config['scaling'][var_y] = {}
    config['scaling'][var_y]["mu"] = df[var_y].mean()
    config['scaling'][var_y]["sigma"] = df[var_y].std()
    
    return (df[var_y] - config['scaling'][var_y]["mu"])/config['scaling'][var_y]["sigma"]


def x_scale(x, p=7.5):
    ''' function for scaling x1
        argument:
            x: the input variable
            p: the scaling factor (default: 7.5)
        returns:
            the scaled variable
    '''
    return 1/p * np.log(1 + x * (np.exp(p) - 1))
                        
    
def y_scale(y):
    ''' function for scaling x1
        argument:
            y: the input variable
        returns:
            the scaled variable
    '''
    return np.log(1 + y) if y >= 0 else -np.log(1 - y)


def y_unscale(y):
    ''' function for scaling x1
        argument:
            y: the input variable
        returns:
            the scaled variable
    '''
    return np.exp(y) - 1 if y >= 0 else 1 - np.exp(-y)

In [39]:
df

{'train':                    x1        x2        x3        x4          y5          y6
 0        5.308962e-08  0.309913  0.050721  0.629043  119.890134 -131.188649
 1        3.505005e-07  0.281701  0.997791  0.482102  -11.651600   15.257625
 2        4.480013e-07  0.609822  0.147178  0.852029  227.064607 -242.366660
 3        6.298025e-07  0.258704  0.408208  0.122103  -27.431008   31.266244
 4        1.014703e-06  0.417312  0.940159  0.743944  111.235489 -114.351289
 ...               ...       ...       ...       ...         ...         ...
 3393721  9.937817e-01  0.520471  0.116823  0.381197   -3.462783   -0.628595
 3393722  9.970094e-01  0.248280  0.539416  0.161634   -5.912596    0.031616
 3393723  9.974963e-01  0.255944  0.522281  0.471605   -7.472055   -0.181993
 3393724  9.976171e-01  0.892835  0.290839  0.270442   -3.183277   -1.728482
 3393725  9.990412e-01  0.747992  0.462169  0.535807   -3.356216   -1.160603

 [3393726 rows x 6 columns],
 'validate':                   x1        x2        x3        x4          y5          y6
 0       5.354692e-07  0.300617  0.526366  0.059579   -8.184049   12.836841
 1       9.024278e-07  0.899253  0.434876  0.475627   82.753550  -85.655862
 2       1.509448e-06  0.827457  0.111961  0.383265  135.201585 -141.116059
 3       2.818238e-06  0.026469  0.460243  0.243116 -307.910481  321.571892
 4       3.436705e-06  0.073680  0.266952  0.102322 -234.340750  245.224692
 ...              ...       ...       ...       ...         ...         ...
 499995  2.508851e-01  0.381725  0.381386  0.696382  -15.352854   -4.878300
 499996  2.509296e-01  0.177722  0.616678  0.067511  -22.578762   -1.033192
 499997  2.513854e-01  0.961017  0.028367  0.942905  -14.607838  -33.053308
 499998  2.516266e-01  0.753230  0.433952  0.703720  -10.080715   -7.518504
 499999  2.521219e-01  0.400000  0.793942  0.387747  -12.021422   -3.451030

 [500000 rows x 6 columns],
 'test':                   x1        x2        x3        x4          y5          y6
 0       5.434361e-07  0.147431  0.774351  0.245984 -174.455943  186.963621
 1       2.254383e-06  0.705441  0.511854  0.034134  152.387746 -158.078358
 2       3.135050e-06  0.348233  0.460954  0.283262   63.641536  -64.647520
 3       3.604113e-06  0.659904  0.123490  0.852356  223.437810 -239.135900
 4       3.774481e-06  0.547915  0.649524  0.693039  171.113443 -177.570199
 ...              ...       ...       ...       ...         ...         ...
 499995  4.796587e-01  0.902703  0.699405  0.882771   -8.360206   -8.187200
 499996  4.803526e-01  0.952353  0.139955  0.355823   -7.330009   -8.443630
 499997  4.804764e-01  0.230907  0.985840  0.120947  -10.881412   -0.363873
 499998  4.811125e-01  0.888229  0.691187  0.302232   -5.679233   -4.133330
 499999  4.812678e-01  0.239973  0.513227  0.599417  -15.277579   -1.359047

 [500000 rows x 6 columns]}

In [40]:
train_loader, validation_loader, test_loader = build_data_loaders(df,config)

/tmp/ipykernel_2387537/3488228483.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y[column] = y[column].apply(lambda y: y_scale(y))
/tmp/ipykernel_2387537/3488228483.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y[column] = y[column].apply(lambda y: y_scale(y))
/tmp/ipykernel_2387537/3488228483.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y[column] = y[column].apply(lambda y: y_scale(y))

In [41]:
t = list(enumerate(test_loader))[:3]

In [42]:
list(test_loader)

[[tensor([[5.4344e-07, 1.4743e-01, 7.7435e-01, 2.4598e-01],
          [2.2544e-06, 7.0544e-01, 5.1185e-01, 3.4134e-02],
          [3.1350e-06, 3.4823e-01, 4.6095e-01, 2.8326e-01],
          ...,
          [9.4767e-04, 7.8192e-01, 8.3783e-01, 9.4324e-01],
          [9.4998e-04, 7.7186e-01, 4.4098e-01, 3.3074e-01],
          [9.5204e-04, 8.9077e-01, 5.2009e-01, 5.5625e-01]], device='cuda:0'),
  tensor([[-5.1674,  5.2362],
          [ 5.0330, -5.0694],
          [ 4.1689, -4.1843],
          ...,
          [ 4.9004, -5.0683],
          [ 4.7817, -5.0497],
          [ 4.6619, -4.6458]], device='cuda:0')],
 [tensor([[9.5312e-04, 5.5020e-01, 6.4033e-01, 9.4720e-01],
          [9.5428e-04, 6.5420e-01, 5.1618e-01, 3.6859e-01],
          [9.5452e-04, 8.7629e-01, 6.2135e-01, 6.7370e-01],
          ...,
          [3.4149e-03, 4.0643e-01, 9.9088e-01, 3.1066e-01],
          [3.4152e-03, 2.4816e-01, 2.5298e-01, 3.1006e-02],
          [3.4161e-03, 8.4951e-01, 9.6366e-01, 3.5161e-01]], device='cuda:0'),
  tensor([[ 4.8820, -5.2430],
          [ 4.7247, -5.1310],
          [ 4.7107, -4.7280],
          ...,
          [ 3.3043, -4.4079],
          [ 2.6668, -4.1388],
          [ 4.3921, -4.8615]], device='cuda:0')],
 [tensor([[0.0034, 0.8970, 0.3620, 0.4070],
          [0.0034, 0.8172, 0.4730, 0.8234],
          [0.0034, 0.5710, 0.6262, 0.9606],
          ...,
          [0.0111, 0.9602, 0.1601, 0.9607],
          [0.0111, 0.6936, 0.5689, 0.2131],
          [0.0111, 0.5994, 0.7254, 0.8798]], device='cuda:0'),
  tensor([[ 4.6904, -4.9003],
          [ 4.6411, -5.1118],
          [ 4.1341, -5.1220],
          ...,
          [ 5.0841, -5.2291],
          [-2.4161, -4.3536],
          [-1.2934, -4.6697]], device='cuda:0')],
 [tensor([[0.0111, 0.9614, 0.1070, 0.8504],
          [0.0111, 0.0107, 0.1931, 0.2887],
          [0.0111, 0.1945, 0.3009, 0.7884],
          ...,
          [0.0307, 0.4256, 0.3929, 0.6789],
          [0.0307, 0.4385, 0.4660, 0.0355],
          [0.0307, 0.0147, 0.9490, 0.9222]], device='cuda:0'),
  tensor([[ 5.0670, -5.2508],
          [-4.8575,  4.0930],
          [-3.3848, -4.9138],
          ...,
          [-3.5385, -3.8383],
          [-3.2527, -3.1461],
          [-4.4868, -6.1986]], device='cuda:0')],
 [tensor([[0.0307, 0.7667, 0.0427, 0.8057],
          [0.0308, 0.5229, 0.4251, 0.2984],
          [0.0308, 0.2034, 0.4563, 0.5513],
          ...,
          [0.0791, 0.2252, 0.6174, 0.0843],
          [0.0792, 0.3400, 0.1968, 0.1031],
          [0.0793, 0.2120, 0.8156, 0.2500]], device='cuda:0'),
  tensor([[-3.0543, -4.2989],
          [-3.2568, -3.5062],
          [-4.2373, -4.0859],
          ...,
          [-3.5990, -2.4069],
          [-3.2139, -2.3517],
          [-3.7702, -2.6878]], device='cuda:0')],
 [tensor([[0.0793, 0.1182, 0.0738, 0.3235],
          [0.0796, 0.4450, 0.2872, 0.2531],
          [0.0796, 0.8742, 0.0972, 0.3441],
          ...,
          [0.1994, 0.6800, 0.4101, 0.2219],
          [0.1996, 0.3716, 0.2033, 0.3199],
          [0.2001, 0.2178, 0.1639, 0.1590]], device='cuda:0'),
  tensor([[-4.5609, -3.2269],
          [-3.0562, -2.5339],
          [-2.8990, -3.4319],
          ...,
          [-2.2670, -1.7696],
          [-2.7486, -1.6527],
          [-3.1838, -1.3399]], device='cuda:0')],
 [tensor([[0.2003, 0.6826, 0.7884, 0.1269],
          [0.2004, 0.2765, 0.3780, 0.5187],
          [0.2007, 0.2938, 0.5110, 0.5616],
          ...,
          [0.5648, 0.9124, 0.9679, 0.2201],
          [0.5649, 0.2865, 0.7840, 0.5360],
          [0.5650, 0.4277, 0.3201, 0.5162]], device='cuda:0'),
  tensor([[-2.1817, -1.6450],
          [-3.1699, -1.8419],
          [-3.1245, -1.8824],
          ...,
          [-1.7908, -1.5522],
          [-2.4551, -0.7510],
          [-2.0735, -0.8941]], device='cuda:0')],
 [tensor([[5.6548e-01, 2.8113e-01, 6.8193e-01, 2.9603e-01],
          [5.6670e-01, 8.5908e-01, 8.8570e-01, 8.9146e-01],
          [5.6708e-01, 7.9910e-01, 3.6079e-01, 3.2845e-01],
          ...,
          [3.3431e-04, 6.1048e-01, 4.5747e-02, 4.0586e-01],
          [3.3639e-04, 6.0475e-01, 9.0293e-01, 2.9045e-01],
          [3.3640e-04, 3.1054e-01, 9.6951e-01, 1.0368e-01]], device='cuda:0'),
  tensor([[-2.3117, -0.5346],
          [-2.0651, -1.8121],
          [-1.7156, -1.1636],
          ...,
          [ 5.1414, -5.3747],
          [ 4.8709, -5.0551],
          [-1.9185,  3.2441]], device='cuda:0')],
 [tensor([[3.3651e-04, 1.9862e-01, 9.2478e-01, 4.5338e-01],
          [3.3691e-04, 7.6479e-01, 9.8624e-01, 3.1386e-01],
          [3.3708e-04, 1.6425e-01, 4.1367e-01, 3.0061e-01],
          ...,
          [1.9120e-03, 4.3638e-02, 4.5953e-01, 9.9555e-01],
          [1.9157e-03, 5.7133e-01, 3.1746e-02, 7.3479e-02],
          [1.9189e-03, 2.4964e-01, 8.1456e-01, 3.1880e-02]], device='cuda:0'),
  tensor([[-4.2815,  4.5706],
          [ 4.8684, -4.9916],
          [-4.3223,  4.6115],
          ...,
          [-5.1266,  5.2938],
          [ 3.8449, -5.0074],
          [ 2.1934,  3.4515]], device='cuda:0')],
 [tensor([[1.9195e-03, 8.3928e-01, 7.3843e-01, 2.7024e-01],
          [1.9241e-03, 2.6458e-01, 3.3974e-02, 5.0073e-04],
          [1.9241e-03, 4.8868e-01, 6.0156e-01, 7.0286e-01],
          ...,
          [6.4223e-03, 3.2650e-01, 8.2691e-01, 7.0073e-01],
          [6.4254e-03, 6.8884e-01, 6.2185e-01, 8.4437e-01],
          [6.4304e-03, 3.7327e-01, 9.1054e-01, 7.4510e-01]], device='cuda:0'),
  tensor([[ 4.5666, -4.8725],
          [ 3.5198, -4.3539],
          [ 4.3553, -5.0520],
          ...,
          [ 2.5273, -4.5620],
          [ 3.5188, -4.9766],
          [ 2.5956, -4.6089]], device='cuda:0')],
 [tensor([[6.4308e-03, 2.1168e-01, 3.5662e-01, 4.7060e-01],
          [6.4328e-03, 4.4369e-01, 9.0555e-01, 5.2942e-01],
          [6.4475e-03, 7.1511e-01, 6.5778e-01, 6.2774e-01],
          ...,
          [1.7924e-02, 4.9528e-02, 4.8150e-04, 9.8156e-01],
          [1.7925e-02, 9.7716e-01, 8.5959e-01, 3.3509e-01],
          [1.7938e-02, 5.7151e-01, 5.8059e-01, 3.3996e-01]], device='cuda:0'),
  tensor([[ 1.3826, -4.6479],
          [ 2.0562, -4.5526],
          [ 3.3780, -4.8990],
          ...,
          [-3.9844, -6.0135],
          [ 4.6055, -4.8666],
          [-3.1137, -3.9979]], device='cuda:0')],
 [tensor([[0.0179, 0.4763, 0.7250, 0.2180],
          [0.0180, 0.7578, 0.8325, 0.6983],
          [0.0180, 0.3694, 0.1076, 0.2460],
          ...,
          [0.0520, 0.4814, 0.4633, 0.4929],
          [0.0521, 0.5254, 0.0274, 0.3126],
          [0.0521, 0.4919, 0.6118, 0.8027]], device='cuda:0'),
  tensor([[-3.1902, -3.7970],
          [-2.1439, -4.4972],
          [-3.6517, -3.9594],
          ...,
          [-3.2696, -3.2027],
          [-3.1671, -3.0677],
          [-3.3336, -3.4435]], device='cuda:0')],
 [tensor([[0.0522, 0.7228, 0.6184, 0.8768],
          [0.0522, 0.2151, 0.6343, 0.9943],
          [0.0522, 0.1526, 0.0576, 0.2560],
          ...,
          [0.1407, 0.1754, 0.8169, 0.1768],
          [0.1408, 0.9150, 0.5925, 0.1972],
          [0.1408, 0.2605, 0.3065, 0.2260]], device='cuda:0'),
  tensor([[-3.1072, -3.7481],
          [-4.2146, -3.8827],
          [-4.4212, -3.4716],
          ...,
          [-3.6363, -1.8614],
          [-2.5896, -2.9310],
          [-3.2596, -1.9055]], device='cuda:0')],
 [tensor([[0.1409, 0.5141, 0.9731, 0.8794],
          [0.1410, 0.3454, 0.0547, 0.6302],
          [0.1410, 0.9677, 0.0750, 0.5637],
          ...,
          [0.3699, 0.7190, 0.0310, 0.6819],
          [0.3701, 0.6443, 0.6192, 0.2336],
          [0.3704, 0.6441, 0.4660, 0.5335]], device='cuda:0'),
  tensor([[-2.9265, -2.5306],
          [-3.2142, -2.3371],
          [-2.8010, -3.9464],
          ...,
          [-2.1608, -1.6708],
          [-1.9067, -1.1626],
          [-2.0990, -1.4354]], device='cuda:0')],
 [tensor([[0.3706, 0.1598, 0.4750, 0.0378],
          [0.3710, 0.7197, 0.6157, 0.2003],
          [0.3711, 0.7952, 0.4355, 0.3369],
          ...,
          [0.9851, 0.7267, 0.1352, 0.2286],
          [0.9856, 0.6849, 0.9241, 0.2143],
          [0.9863, 0.0849, 0.0032, 0.9983]], device='cuda:0'),
  tensor([[-2.9788,  0.2443],
          [-1.8625, -1.2310],
          [-1.9823, -1.5427],
          ...,
          [-1.2833, -0.5642],
          [-1.2866, -0.5007],
          [-3.6559,  1.4073]], device='cuda:0')],
 [tensor([[9.8656e-01, 1.2888e-02, 1.4755e-02, 2.9334e-01],
          [9.9007e-01, 5.5300e-01, 9.6303e-01, 9.4494e-01],
          [9.9010e-01, 9.9865e-01, 5.9492e-01, 7.1800e-01],
          ...,
          [9.3130e-04, 6.0373e-01, 4.9440e-01, 5.8340e-01],
          [9.3158e-04, 4.2216e-01, 7.6621e-01, 2.8407e-01],
          [9.3363e-04, 9.1727e-01, 3.5380e-01, 6.9480e-01]], device='cuda:0'),
  tensor([[-5.3810,  3.2575],
          [-1.7429, -0.7939],
          [-3.1649, -4.0718],
          ...,
          [ 4.8081, -5.2033],
          [ 4.2306, -4.5869],
          [ 4.6045, -4.5016]], device='cuda:0')],
 [tensor([[9.3621e-04, 8.9214e-01, 7.5240e-01, 8.9073e-01],
          [9.3716e-04, 7.7150e-01, 9.6754e-01, 1.9871e-01],
          [9.3783e-04, 8.3876e-02, 8.1011e-01, 1.9784e-01],
          ...,
          [3.3470e-03, 7.6968e-01, 2.7741e-01, 5.6619e-01],
          [3.3534e-03, 9.6684e-01, 5.4257e-01, 8.2649e-01],
          [3.3554e-03, 3.8712e-02, 3.6031e-01, 3.3935e-02]], device='cuda:0'),
  tensor([[ 4.6479, -4.6265],
          [ 4.6810, -4.9663],
          [-5.4426,  5.6696],
          ...,
          [ 4.3841, -5.1328],
          [ 4.5488, -4.0663],
          [-5.4520,  5.7834]], device='cuda:0')],
 [tensor([[0.0034, 0.5534, 0.5109, 0.3220],
          [0.0034, 0.4263, 0.7167, 0.2155],
          [0.0034, 0.4045, 0.6193, 0.9834],
          ...,
          [0.0098, 0.9573, 0.9911, 0.5361],
          [0.0098, 0.9794, 0.4195, 0.5062],
          [0.0098, 0.6305, 0.4805, 0.7923]], device='cuda:0'),
  tensor([[ 3.4600, -4.8469],
          [ 3.1621, -4.5064],
          [ 4.0095, -4.9875],
          ...,
          [ 4.6596, -4.7498],
          [ 5.0242, -4.7200],
          [ 0.7730, -4.7570]], device='cuda:0')],
 [tensor([[0.0098, 0.9202, 0.0137, 0.5036],
          [0.0098, 0.7732, 0.8667, 0.2115],
          [0.0098, 0.2287, 0.4919, 0.8384],
          ...,
          [0.0298, 0.1263, 0.0491, 0.5624],
          [0.0299, 0.5738, 0.2654, 0.7330],
          [0.0299, 0.9305, 0.1332, 0.4050]], device='cuda:0'),
  tensor([[ 4.3612, -5.2017],
          [ 1.1871, -4.5114],
          [-2.5759, -4.7823],
          ...,
          [-4.8455, -4.6649],
          [-3.3028, -3.9538],
          [-1.0184, -4.7195]], device='cuda:0')],
 [tensor([[0.0299, 0.0938, 0.1908, 0.5198],
          [0.0299, 0.9221, 0.2309, 0.4245],
          [0.0299, 0.4048, 0.6675, 0.7930],
          ...,
          [0.0785, 0.7859, 0.6461, 0.1353],
          [0.0785, 0.8244, 0.8427, 0.1070],
          [0.0786, 0.3058, 0.0423, 0.6655]], device='cuda:0'),
  tensor([[-5.0649, -4.9123],
          [-1.5343, -4.6595],
          [-3.5412, -3.9152],
          ...,
          [-2.7065, -2.8175],
          [-2.6890, -2.8998],
          [-3.6637, -3.0359]], device='cuda:0')],
 [tensor([[0.0786, 0.5109, 0.5999, 0.1574],
          [0.0786, 0.8401, 0.7446, 0.5244],
          [0.0788, 0.5468, 0.0765, 0.3009],
          ...,
          [0.2250, 0.0347, 0.8275, 0.9322],
          [0.2252, 0.5906, 0.3815, 0.0459],
          [0.2253, 0.4895, 0.1535, 0.8333]], device='cuda:0'),
  tensor([[-2.8643, -2.4318],
          [-2.9088, -3.4359],
          [-2.9443, -2.6532],
          ...,
          [-5.6325, -3.8031],
          [-2.0940, -1.3249],
          [-2.7087, -2.0246]], device='cuda:0')],
 [tensor([[0.2253, 0.8404, 0.6761, 0.7181],
          [0.2254, 0.4249, 0.7697, 0.6263],
          [0.2259, 0.4789, 0.0786, 0.9895],
          ...,
          [0.6277, 0.5950, 0.5995, 0.9057],
          [0.6277, 0.6902, 0.5234, 0.0856],
          [0.6292, 0.2316, 0.2595, 0.5000]], device='cuda:0'),
  tensor([[-2.5215, -2.5409],
          [-2.7184, -1.8311],
          [-2.7879, -2.1250],
          ...,
          [-1.9775, -1.1661],
          [-1.4513, -0.6719],
          [-2.5819, -0.4450]], device='cuda:0')],
 [tensor([[6.3073e-01, 7.5390e-01, 9.3596e-01, 5.8142e-01],
          [6.3161e-01, 1.3589e-01, 7.4267e-01, 1.3057e-01],
          [6.3176e-01, 4.3660e-01, 3.7179e-01, 7.3680e-01],
          ...,
          [4.0402e-04, 7.6096e-02, 4.4692e-01, 9.9007e-01],
          [4.0524e-04, 9.2546e-01, 5.8663e-02, 4.5308e-01],
          [4.0564e-04, 8.3670e-01, 4.4773e-01, 5.3390e-01]], device='cuda:0'),
  tensor([[-1.7776, -1.1701],
          [-2.8701,  0.7683],
          [-2.1012, -0.9546],
          ...,
          [-4.9141,  5.0146],
          [ 4.4816, -4.4045],
          [ 4.8258, -4.8855]], device='cuda:0')],
 [tensor([[4.0645e-04, 2.8594e-01, 5.6400e-01, 4.6474e-01],
          [4.0698e-04, 5.3273e-01, 7.5746e-01, 2.6471e-01],
          [4.0797e-04, 6.7648e-01, 1.4893e-01, 2.4508e-01],
          ...,
          [2.1275e-03, 7.4905e-01, 4.1113e-01, 7.4108e-01],
          [2.1351e-03, 6.5854e-01, 1.7927e-01, 9.9577e-01],
          [2.1358e-03, 4.8467e-01, 6.5223e-02, 8.2224e-01]], device='cuda:0'),
  tensor([[ 3.6249, -3.5139],
          [ 4.7391, -4.9634],
          [ 4.9900, -5.2248],
          ...,
          [ 4.6961, -5.1845],
          [ 4.7343, -5.3873],
          [ 4.4548, -5.3449]], device='cuda:0')],
 [tensor([[0.0021, 0.0125, 0.0775, 0.7790],
          [0.0021, 0.0453, 0.9437, 0.8700],
          [0.0021, 0.1465, 0.7575, 0.0904],
          ...,
          [0.0068, 0.4054, 0.3716, 0.5657],
          [0.0068, 0.2083, 0.5256, 0.6575],
          [0.0068, 0.3927, 0.2810, 0.2109]], device='cuda:0'),
  tensor([[-5.6603,  5.5311],
          [-5.4822,  5.5976],
          [-3.7840,  4.9148],
          ...,
          [-1.0589, -4.7162],
          [ 2.4378, -4.6150],
          [-2.6102, -4.4644]], device='cuda:0')],
 [tensor([[0.0068, 0.8427, 0.0308, 0.5213],
          [0.0068, 0.5288, 0.3740, 0.6523],
          [0.0068, 0.8472, 0.1526, 0.7687],
          ...,
          [0.0185, 0.4547, 0.6239, 0.3697],
          [0.0186, 0.0013, 0.7094, 0.2168],
          [0.0186, 0.4258, 0.8897, 0.7017]], device='cuda:0'),
  tensor([[ 4.0279, -5.1338],
          [ 1.7792, -4.8097],
          [ 4.2982, -5.1786],
          ...,
          [-3.2950, -3.9392],
          [-8.0784,  7.0463],
          [-3.2541, -4.1581]], device='cuda:0')],
 [tensor([[1.8581e-02, 1.3054e-04, 7.7743e-01, 3.9147e-01],
          [1.8595e-02, 5.3911e-01, 8.4740e-01, 1.2663e-01],
          [1.8599e-02, 7.2633e-01, 8.8420e-01, 8.3274e-01],
          ...,
          [4.8775e-02, 2.6525e-01, 7.5371e-02, 5.3490e-02],
          [4.8797e-02, 4.6082e-01, 7.8153e-01, 6.2489e-01],
          [4.8858e-02, 3.5935e-01, 7.3112e-01, 6.6007e-01]], device='cuda:0'),
  tensor([[-8.6006,  6.8955],
          [-3.0612, -3.6790],
          [-2.3115, -4.4893],
          ...,
          [-3.6868, -2.8744],
          [-3.3312, -3.3519],
          [-3.5787, -3.4167]], device='cuda:0')],
 [tensor([[0.0490, 0.2154, 0.8007, 0.1949],
          [0.0490, 0.4567, 0.9346, 0.1984],
          [0.0491, 0.6425, 0.1791, 0.2631],
          ...,
          [0.1377, 0.0867, 0.9182, 0.4874],
          [0.1377, 0.3024, 0.5269, 0.2498],
          [0.1379, 0.4789, 0.5200, 0.1297]], device='cuda:0'),
  tensor([[-3.8812, -3.1423],
          [-3.1285, -2.9080],
          [-3.0318, -3.1672],
          ...,
          [-4.6603, -2.8618],
          [-3.1209, -1.9543],
          [-2.5954, -1.8237]], device='cuda:0')],
 [tensor([[0.1380, 0.3604, 0.5974, 0.4860],
          [0.1383, 0.0733, 0.2367, 0.3652],
          [0.1384, 0.3523, 0.5050, 0.0613],
          ...,
          [0.3819, 0.0617, 0.0558, 0.7579],
          [0.3823, 0.7147, 0.2028, 0.0539],
          [0.3826, 0.8446, 0.4800, 0.2768]], device='cuda:0'),
  tensor([[-3.0873, -2.2097],
          [-4.8185, -2.7951],
          [-2.8064, -1.6840],
          ...,
          [-4.5927, -0.2492],
          [-1.7235, -1.0327],
          [-1.9628, -1.6189]], device='cuda:0')],
 [tensor([[3.8292e-01, 7.6641e-01, 9.6658e-01, 1.9299e-01],
          [3.8300e-01, 8.9713e-01, 3.8338e-01, 4.4480e-01],
          [3.8328e-01, 3.2725e-01, 6.6101e-01, 8.2341e-01],
          ...,
          [2.2953e-05, 4.9786e-01, 4.9987e-01, 8.5787e-01],
          [2.4166e-05, 5.0930e-01, 9.3276e-01, 4.9814e-01],
          [2.5104e-05, 1.9900e-01, 6.0490e-01, 1.6626e-01]], device='cuda:0'),
  tensor([[-1.8430, -1.2860],
          [-2.1496, -2.0561],
          [-2.7329, -1.4061],
          ...,
          [ 5.1822, -5.2383],
          [ 4.9289, -4.9663],
          [-4.6434,  4.7444]], device='cuda:0')],
 [tensor([[2.5305e-05, 4.0034e-01, 2.3350e-02, 3.4286e-01],
          [2.5822e-05, 3.8391e-01, 2.3147e-02, 1.4848e-01],
          [2.5873e-05, 8.6522e-01, 4.3869e-01, 8.9138e-01],
          ...,
          [1.0074e-03, 3.0393e-01, 9.2533e-02, 6.8441e-01],
          [1.0106e-03, 4.4633e-01, 9.9894e-01, 1.6184e-02],
          [1.0108e-03, 3.9456e-01, 7.9003e-01, 3.6280e-01]], device='cuda:0'),
  tensor([[ 5.0190, -5.0912],
          [ 4.7877, -4.8468],
          [ 4.7438, -4.7867],
          ...,
          [ 4.6229, -4.9869],
          [ 3.9403, -4.3395],
          [ 4.1680, -4.4957]], device='cuda:0')],
 [tensor([[0.0010, 0.3760, 0.5808, 0.4277],
          [0.0010, 0.3089, 0.4359, 0.7496],
          [0.0010, 0.1778, 0.6410, 0.8372],
          ...,
          [0.0036, 0.8506, 0.0014, 0.5016],
          [0.0036, 0.2070, 0.3913, 0.8634],
          [0.0036, 0.1106, 0.3355, 0.6302]], device='cuda:0'),
  tensor([[ 4.2609, -4.6074],
          [ 4.3762, -4.6335],
          [-1.9412,  3.5130],
          ...,
          [ 4.6618, -5.2006],
          [ 3.9704, -4.5979],
          [ 3.4278, -1.1773]], device='cuda:0')],
 [tensor([[0.0036, 0.7149, 0.5254, 0.4452],
          [0.0036, 0.3402, 0.0480, 0.1396],
          [0.0036, 0.3854, 0.8298, 0.1676],
          ...,
          [0.0109, 0.5967, 0.7230, 0.7121],
          [0.0109, 0.1732, 0.9558, 0.8699],
          [0.0109, 0.9074, 0.8366, 0.6603]], device='cuda:0'),
  tensor([[ 3.9838, -4.9990],
          [ 2.2426, -4.7251],
          [ 2.9584, -4.2720],
          ...,
          [-1.8533, -4.5893],
          [-1.6668, -4.4899],
          [ 4.1896, -4.9479]], device='cuda:0')],
 [tensor([[0.0109, 0.1456, 0.9239, 0.1922],
          [0.0109, 0.1886, 0.8480, 0.5667],
          [0.0109, 0.5889, 0.7772, 0.7437],
          ...,
          [0.0304, 0.6420, 0.6454, 0.2923],
          [0.0305, 0.7046, 0.9749, 0.4933],
          [0.0305, 0.4225, 0.6701, 0.7588]], device='cuda:0'),
  tensor([[-3.1690, -3.7356],
          [-2.8334, -4.3707],
          [-1.7957, -4.5896],
          ...,
          [-3.0876, -3.5974],
          [-3.0073, -3.8598],
          [-3.4979, -3.8691]], device='cuda:0')],
 [tensor([[0.0306, 0.1433, 0.3363, 0.2095],
          [0.0306, 0.2110, 0.4366, 0.8010],
          [0.0306, 0.1121, 0.3896, 0.1003],
          ...,
          [0.0890, 0.7160, 0.6951, 0.1457],
          [0.0890, 0.7278, 0.2422, 0.1970],
          [0.0890, 0.5009, 0.4660, 0.3611]], device='cuda:0'),
  tensor([[-4.5229, -4.0275],
          [-4.2527, -4.2727],
          [-4.7032, -4.0758],
          ...,
          [-2.6434, -2.5316],
          [-2.7009, -2.6410],
          [-2.9578, -2.5526]], device='cuda:0')],
 [tensor([[0.0892, 0.9555, 0.3337, 0.3034],
          [0.0893, 0.4672, 0.3193, 0.3287],
          [0.0893, 0.3853, 0.7202, 0.5163],
          ...,
          [0.2363, 0.3948, 0.1711, 0.6664],
          [0.2368, 0.8138, 0.2020, 0.0622],
          [0.2369, 0.7597, 0.6681, 0.1940]], device='cuda:0'),
  tensor([[-2.7828, -3.9467],
          [-3.0022, -2.5088],
          [-3.2493, -2.6852],
          ...,
          [-2.7887, -1.8147],
          [-2.0618, -1.7041],
          [-2.1383, -1.7200]], device='cuda:0')],
 [tensor([[0.2370, 0.6263, 0.7362, 0.8361],
          [0.2370, 0.2069, 0.2732, 0.9359],
          [0.2373, 0.2447, 0.3144, 0.7646],
          ...,
          [0.6633, 0.2828, 0.9015, 0.8999],
          [0.6641, 0.0336, 0.9159, 0.8488],

In [43]:
def test_model(model, test_data, config):
    ''' function for testing the model
        arguments:
            model: the pytorch model to nbe trained
            test_data: the test data loader
            config: the configurations file
        returns:
            the absolute error
            the R2 score
    '''
    
    for i, data in enumerate(test_data):
        
        # forward prop
        x, y = data
        y_p = model(x)
        
        # store data
        if i == 0:
            x_test = x.cpu().detach().numpy()
            y_test = y.cpu().detach().numpy()
            y_pred = y_p.cpu().detach().numpy()
        else: 
            x_test = np.vstack((x_test, x.cpu().detach().numpy()))
            y_test = np.vstack((y_test, y.cpu().detach().numpy()))
            y_pred = np.vstack((y_pred, y_p.cpu().detach().numpy()))
        
    
    # accuracy
    y_test = np.array(y_test).reshape(-1, config['n_targets'])
    y_pred = np.array(y_pred).reshape(-1, config['n_targets'])
    abs_score = (1 - np.mean(np.abs((y_pred - y_test)/y_test)))*100
    r2_score = metrics.r2_score(y_test, y_pred)*100
    
    # save test results
    df_pred = pd.DataFrame(x_test, columns=['x'+str(i+1) for i in range(config['input_shape'])])
    
    # unscale the target
    scaled_cname = [s + '_scaled' for s in config['var_y']]
    df_pred = pd.concat([df_pred, pd.DataFrame(y_test, columns=scaled_cname)], axis=1)
    for col in df_pred.columns[4:]:
        df_pred[col[:-7]] = df_pred[col].apply(lambda y: y_unscale(y))
    # y_test_real = pd.DataFrame(np.vectorize(y_unscale)(y_test), columns=config['var_y']) # 
    # df_pred = pd.concat([df_pred, y_test_real], axis=1)
    y_test_real = df_pred.iloc[:,-config['n_targets']:].to_numpy()
    
    # stuff in the scaled predictions
    pred_cname = [s + '_scaled_pred' for s in config['var_y']]
    df_pred = pd.concat([df_pred, pd.DataFrame(y_pred, columns=pred_cname)], axis=1)
    
    # stuff in the unscaled predictions
    pred_cname = [s + '_pred' for s in config['var_y']]
    for col in df_pred.columns[-config['n_targets']:]:
        df_pred[col[:-12]+'_pred'] = df_pred[col].apply(lambda y: y_unscale(y))
    # y_pred_real = pd.DataFrame(np.vectorize(y_unscale)(y_pred), columns=pred_cname) # .apply(lambda y: y_unscale(y))
    # df_pred = pd.concat([df_pred, y_pred_real], axis=1)
    y_pred_real = df_pred.iloc[:,-config['n_targets']:].to_numpy()
    
    # calculate the deltas for the scaled and unscaled targets
    scaled_delta_cname = ['scaled_delta_' + s for s in config['var_y']]
    df_pred = pd.concat([df_pred, pd.DataFrame((y_pred - y_test)/y_test*100, columns=scaled_delta_cname)], axis=1)
    delta_cname = ['delta_' + s for s in config['var_y']]
    df_pred = pd.concat([df_pred, pd.DataFrame((y_pred_real - y_test_real)/y_test_real*100, columns=delta_cname)], axis=1)
    
    #same the whole dataframe
    #df_pred.to_csv(config['directory']+'/test-results-'+config['model-uuid']+'-'+f'{abs_score:.6f}-{r2_score:.6f}.csv')
    
    # plot all the scaled and real deltas
    """for c in scaled_delta_cname:
        make_error_plot(config, df_pred, col=c)
    for c in delta_cname:
        make_error_plot(config, df_pred, col=c)"""
        
    config['test_metrics'] = {}
    config['test_metrics']['r2'] = {}
    config['test_metrics']['abs_score'] = {}
    num_vars = len(config['var_y'])
    base_length = config['input_shape'] + num_vars
    for i in range(base_length, base_length + num_vars):
        test = df_pred.iloc[:,i].values
        pred = df_pred.iloc[:,i + 2 * num_vars].values
        config['test_metrics']['r2'][config['var_y'][i - base_length]] = metrics.r2_score(test, pred)*100
        config['test_metrics']['abs_score'][config['var_y'][i - base_length]] = 100 - np.abs(df_pred.iloc[:,i + 4 * num_vars].mean())
    
    config['test_metrics']['r2']['model'] = r2_score
    config['test_metrics']['abs_score']['model'] = abs_score
    
    return abs_score, r2_score

## Model classes

In [24]:
class EarlyStopping:
    ''' class for early stopping with patience
    '''
    def __init__(self, m_path, patience=1, min_delta=0):
        '''
            arguments:
                m_path: the model path where the checkpoints go
                patience: the number of epochs the patience lasts
                min_delta: the minimum change that is monitored
        '''
        self.patience = patience
        self.min_delta = min_delta
        self.counter = 0
        self.min_validation_loss = np.inf
        self.m_path = m_path
        
    def reset_counter(self):
        ''' function to reset the counter
        '''
        self.counter = 0

    def early_stop(self, model, validation_loss, epoch, config):
        ''' function to check for the early stopping threshold
            arguments:
                model: the torch model
                validation_loss: the validation loss
        '''
        if epoch > config['early_stopping_start_epoch']: 
            if validation_loss < self.min_validation_loss:
                self.min_validation_loss = validation_loss
                torch.save(model.state_dict(), self.m_path)
                config['n_training_epochs'] = epoch
                self.counter = 0
            elif validation_loss > (self.min_validation_loss + self.min_delta):
                self.counter += 1
                if self.counter >= self.patience:
                    return True
            return False
        else:
            return False
    
    
class skip_block(torch.nn.Module):
    """ the basic building block of a dnn with skip connections
        arguments:
            x: the input
            width: the width of the hidden layers
            activation: the activation function: 'relu', 'elu', 'swish' (silu), 'leaky_relu', 'softplus'
            squeeze: a boolean specifying wheher the skip units are squeezed
        returns:
            res: the skip net block
    """
    def __init__(self, input_shape, width, activation, stream = False, n_layers=1):
        ''' init function
            arguments:
                input_shape: the input shape of the block
                width: the width of the block
                activation: the activation function
                stream: build a residual stream or not (default: false)
                n_layers: the number of layers in the block (default: 1)
        '''
        super(skip_block, self).__init__()
        self.input_shape = input_shape
        self.width = width
        self.stream = stream
        
        self.input = torch.nn.Linear(self.input_shape, self.width)
        self.fc_module = torch.nn.ModuleList([torch.nn.Linear(self.width, self.width) for i in range(n_layers)])
        
        if self.stream:
            self.linear = torch.nn.Linear(self.width, self.input_shape)
        else:    
            self.linear = torch.nn.Linear(self.width, self.width)
            
        if self.input_shape != self.width:
            self.reshape = torch.nn.Linear(self.input_shape, self.width, bias=False)
        
        self.act = activation
        
    def forward(self, x):
        ''' forward propagation
        '''
        y = self.act(self.input(x))
        for l in self.fc_module:
            y = self.act(l(y))
        if self.stream:
            y = self.act(self.linear(y))
            y += x
            return y
        else:
            y = self.linear(y)
            if self.input_shape != self.width:
                residual = self.reshape(x)
            else:
                residual = x
            y += residual

            return self.act(y)
        
        
def getActivation(config):
    ''' function for defining the activation function
        argument:
            config: the configurations file
        returns
            the specified activations function
    '''
    if config["activation"] == 'leaky_relu':
        return torch.nn.LeakyReLU()
    elif config["activation"] == 'relu':
        return torch.nn.ReLU()
    if config["activation"] == 'softplus':
        return torch.nn.Softplus()
    if config["activation"] == 'swish':
        return torch.nn.SiLU()
    if config["activation"] == 'sigmoid':
        return torch.nn.Sigmoid()
        
    
class skip_dnn(torch.nn.Module):
    ''' class for the DNN with skip connections: see https://arxiv.org/abs/2302.00753
    '''
    def __init__(self, sk_block, config, stream = False):
        super(skip_dnn, self).__init__()
        self.width = config["width"]
        self.n_blocks = config["depth"] - 1
        self.input_shape = config["input_shape"]
        self.output_shape = config['n_targets']
        self.n_layers = config['skip_block_layers']
        self.stream = stream
        self.act = getActivation(config)
        
        self.input = skip_block(self.input_shape, 
                                self.width, 
                                self.act, 
                                stream = self.stream, 
                                n_layers = self.n_layers)
        self.core = self.make_layers(skip_block)
        if self.stream: 
            self.output = torch.nn.Linear(self.input_shape, self.output_shape)
        else: 
            self.output = torch.nn.Linear(self.width, self.output_shape)
            
    def make_layers(self, skip_block):
        layers = []
        for bl in range(self.n_blocks):
            if self.stream: 
                layers.append(skip_block(self.input_shape, 
                                         self.width, 
                                         self.act, 
                                         stream=self.stream, 
                                         n_layers = self.n_layers))
            else:
                layers.append(skip_block(self.width, 
                                         self.width, 
                                         self.act, 
                                         n_layers = self.n_layers))
            
        return torch.nn.Sequential(*layers)
        
    def forward(self, x):
        x = self.input(x)
        x = self.core(x)
        return self.output(x)
    
    
class dnn(torch.nn.Module):
    ''' class for a feed-forward DNN
    '''
    def __init__(self, config):
        super(dnn, self).__init__()
        self.width = config["width"]
        
        self.input = torch.nn.Linear(config["input_shape"], self.width)
        self.fc_module = torch.nn.ModuleList([torch.nn.Linear(self.width, self.width) for i in range(config["depth"] - 1)])
        self.output = torch.nn.Linear(self.width, config['n_targets'])
        self.act = getActivation(config)
        
    def forward(self, x):
        x = self.act(self.input(x))
        for l in self.fc_module:
            x = self.act(l(x))
        return self.output(x)



class skip_light_module(torch.nn.Module):
    """ 
        This is a skip dnn component of the skip_light neural network 
        argument:
            config: the configurations file
    """
    def __init__(self, config):
        super(skip_light_module, self).__init__()
        self.width = config["width"]
        self.skip_layer_depth = config["skip_block_layers"]
        self.act = getActivation(config)
        self.fc_module = torch.nn.ModuleList([torch.nn.Linear(self.width, self.width) 
                                              for i in range(self.skip_layer_depth)])
        # Apply Xavier (Glorot) normal initialization to layers of fc_module
        for layer in self.fc_module:
            torch.nn.init.xavier_normal_(layer.weight)
            torch.nn.init.zeros_(layer.bias)
        
    def forward(self, x):
        y = x
        # vector x shape and width are the same
        for layer in self.fc_module:
            y = self.act(layer(y))
        y = y+x
        return y
    
class skip_light(torch.nn.Module):
    """
        implementation of the skip network as a lighter version of the skip_dnn, based on Fady's implementation
        argument:
            config: the configurations file
    """
    def __init__(self, config):
        super(skip_light, self).__init__()
        self.input_shape = config["input_shape"]
        self.width = config["width"]
        self.n_modules = config["depth"]
        self.skip_depth = config["skip_block_layers"]
        self.output_shape = config['n_targets']
        
        # input layer
        self.input = torch.nn.Linear(self.input_shape, self.width)
        torch.nn.init.xavier_normal_(self.input.weight)  # Equivalent to 'glorot_normal'
        torch.nn.init.zeros_(self.input.bias)  # Equivalent to 'zeros'
        self.act = getActivation(config)
        #skip blocks
        self.skip_core = torch.nn.Sequential(*[
            skip_light_module(config) 
            for _ in range(self.n_modules)
        ])
        #output layer
        self.output = torch.nn.Linear(self.width, self.output_shape)
        torch.nn.init.xavier_normal_(self.output.weight)  # Equivalent to 'glorot_normal'
        torch.nn.init.zeros_(self.output.bias)  # Equivalent to 'zeros'
        
    def forward(self, x):
        x = self.act(self.input(x))
        x = self.skip_core(x)
        x = self.output(x)
        return x
    
    
def nets(config):
    """ the pytorch model builder
        arguments:
            config: the configuration file
        returns:
            regressor: the pytorch model
    """
    
    # define the torch model
    if config["model_type"] == 'dnn':
        regressor = dnn(config).double().to(get_device())
    elif config["model_type"] == 'skip':
        regressor = skip_dnn(skip_block, config).double().to(get_device())
    elif config["model_type"] == 'skip-stream':
        regressor = skip_dnn(skip_block, config, stream = True).double().to(get_device())
    elif config["model_type"] == 'skip-light':
        regressor = skip_light(config).double().to(get_device())
    else:
        logging.error(' '+config["model_type"]+' not implemented. model_type can be either dnn, skip or squeeze')
        
        
    # save parameter counts
    summary = pms.summary(regressor, torch.zeros((config["input_shape"],)).to(get_device()).double().clone().detach().requires_grad_(True)).rstrip().split('\n')
    config["trainable_parameters"] = int(summary[-3].replace(',', '')[18:])
    config["non_trainable_parameters"] = int(summary[-2].replace(',', '')[22:])
    config["total_parameters"] = int(summary[-4].replace(',', '')[14:])
    
    # save config
    with open(config['directory']+'/config-'+config['model-uuid']+'.json', 'w') as f:
        json.dump(config, f, indent=4)
        
    return regressor

## Load Model

In [4]:
model_path = "../models/skip-light-torch-4D-y5_y6-ef8e7636--10-31-leaky_relu-1024-adam-exp-schedule-mse-val_mse-97.017682-99.836771/dnn-10-31-leaky_relu-adam-exp-schedule-mse-val_mse.torch" #"../models/run1/skip-torch-4D-y5-55960c0a--16-32-leaky_relu-512-adam-exp-schedule-mse-val_mse-94.928634-99.670260/dnn-16-32-leaky_relu-adam-exp-schedule-mse-val_mse.torch" #"../run1/" + config['directory'] + f'/dnn-{config["depth"]}-{config["width"]}-{config["activation"]}-adam-{config["lr_decay_type"]}-schedule-{config["loss"]}-{config["monitor"]}.torch'

In [33]:
"""models/run1/skip-torch-4D-y5-55960c0a--16-32-leaky_relu-512-adam-exp-schedule-mse-val_mse-94.928634-99.670260/dnn-16-32-leaky_relu-adam-exp-schedule-mse-val_mse.torch"""

'models/run1/skip-torch-4D-y5-55960c0a--16-32-leaky_relu-512-adam-exp-schedule-mse-val_mse-94.928634-99.670260/dnn-16-32-leaky_relu-adam-exp-schedule-mse-val_mse.torch'

In [5]:
!ls {model_path}

../models/skip-light-torch-4D-y5_y6-ef8e7636--10-31-leaky_relu-1024-adam-exp-schedule-mse-val_mse-97.017682-99.836771/dnn-10-31-leaky_relu-adam-exp-schedule-mse-val_mse.torch

In [25]:
# define the torch model
if config["model_type"] == 'dnn':
    regressor = dnn(config).double().to(get_device())
elif config["model_type"] == 'skip':
    regressor = skip_dnn(skip_block, config).double().to(get_device())
elif config["model_type"] == 'skip-stream':
    regressor = skip_dnn(skip_block, config, stream = True).double().to(get_device())
elif config["model_type"] == 'skip-light':
    regressor = skip_light(config).double().to(get_device())
else:
    logging.error(' '+config["model_type"]+' not implemented. model_type can be either dnn, skip or squeeze')

In [28]:
regressor.load_state_dict(torch.load(model_path, map_location=torch.device('cpu')))

/tmp/ipykernel_2387537/1709965805.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  regressor.load_state_dict(torch.load(model_path, map_location=torch.device('cpu')))

In [44]:
abs_score, r2_score = test_model(regressor, test_loader, config)

In [45]:
print(' relative accuracy: {:.2f}%  |---|  R2 score: {:.2f}%'.format(abs_score, r2_score))

 relative accuracy: 97.02%  |---|  R2 score: 99.84%

In [46]:
def test_model(model, test_data, config):
    ''' function for testing the model
        arguments:
            model: the pytorch model to nbe trained
            test_data: the test data loader
            config: the configurations file
        returns:
            the absolute error
            the R2 score
    '''
    
    for i, data in enumerate(test_data):
        
        # forward prop
        x, y = data
        y_p = model(x)
        
        # store data
        if i == 0:
            x_test = x.cpu().detach().numpy()
            y_test = y.cpu().detach().numpy()
            y_pred = y_p.cpu().detach().numpy()
        else: 
            x_test = np.vstack((x_test, x.cpu().detach().numpy()))
            y_test = np.vstack((y_test, y.cpu().detach().numpy()))
            y_pred = np.vstack((y_pred, y_p.cpu().detach().numpy()))
        
    
    # accuracy
    y_test = np.array(y_test).reshape(-1, config['n_targets'])
    y_pred = np.array(y_pred).reshape(-1, config['n_targets'])
    abs_score = (1 - np.mean(np.abs((y_pred - y_test)/y_test)))*100
    r2_score = metrics.r2_score(y_test, y_pred)*100
    
    # save test results
    df_pred = pd.DataFrame(x_test, columns=['x'+str(i+1) for i in range(config['input_shape'])])
    
    # unscale the target
    scaled_cname = [s + '_scaled' for s in config['var_y']]
    df_pred = pd.concat([df_pred, pd.DataFrame(y_test, columns=scaled_cname)], axis=1)
    for col in df_pred.columns[4:]:
        df_pred[col[:-7]] = df_pred[col].apply(lambda y: y_unscale(y))
    # y_test_real = pd.DataFrame(np.vectorize(y_unscale)(y_test), columns=config['var_y']) # 
    # df_pred = pd.concat([df_pred, y_test_real], axis=1)
    y_test_real = df_pred.iloc[:,-config['n_targets']:].to_numpy()
    
    # stuff in the scaled predictions
    pred_cname = [s + '_scaled_pred' for s in config['var_y']]
    df_pred = pd.concat([df_pred, pd.DataFrame(y_pred, columns=pred_cname)], axis=1)
    
    # stuff in the unscaled predictions
    pred_cname = [s + '_pred' for s in config['var_y']]
    for col in df_pred.columns[-config['n_targets']:]:
        df_pred[col[:-12]+'_pred'] = df_pred[col].apply(lambda y: y_unscale(y))
    # y_pred_real = pd.DataFrame(np.vectorize(y_unscale)(y_pred), columns=pred_cname) # .apply(lambda y: y_unscale(y))
    # df_pred = pd.concat([df_pred, y_pred_real], axis=1)
    y_pred_real = df_pred.iloc[:,-config['n_targets']:].to_numpy()
    
    # calculate the deltas for the scaled and unscaled targets
    scaled_delta_cname = ['scaled_delta_' + s for s in config['var_y']]
    df_pred = pd.concat([df_pred, pd.DataFrame((y_pred - y_test)/y_test*100, columns=scaled_delta_cname)], axis=1)
    delta_cname = ['delta_' + s for s in config['var_y']]
    df_pred = pd.concat([df_pred, pd.DataFrame((y_pred_real - y_test_real)/y_test_real*100, columns=delta_cname)], axis=1)
    
    #same the whole dataframe
    #df_pred.to_csv(config['directory']+'/test-results-'+config['model-uuid']+'-'+f'{abs_score:.6f}-{r2_score:.6f}.csv')
    
    # plot all the scaled and real deltas
    """for c in scaled_delta_cname:
        make_error_plot(config, df_pred, col=c)
    for c in delta_cname:
        make_error_plot(config, df_pred, col=c)"""
        
    config['test_metrics'] = {}
    config['test_metrics']['r2'] = {}
    config['test_metrics']['abs_score'] = {}
    num_vars = len(config['var_y'])
    base_length = config['input_shape'] + num_vars
    for i in range(base_length, base_length + num_vars):
        test = df_pred.iloc[:,i].values
        pred = df_pred.iloc[:,i + 2 * num_vars].values
        config['test_metrics']['r2'][config['var_y'][i - base_length]] = metrics.r2_score(test, pred)*100
        config['test_metrics']['abs_score'][config['var_y'][i - base_length]] = 100 - np.abs(df_pred.iloc[:,i + 4 * num_vars].mean())
    
    config['test_metrics']['r2']['model'] = r2_score
    config['test_metrics']['abs_score']['model'] = abs_score
    
    return abs_score, r2_score

In [47]:
df_pred

NameError: name 'df_pred' is not defined

In [57]:
df_pred

,x1,x2,x3,x4,y5_scaled,y5,y5_scaled_pred,y5_pred,scaled_delta_y5,delta_y5
0,5.434361e-07,0.147431,0.774351,0.245984,-5.167388,-174.455943,-5.089776,-161.353522,-1.501954,-7.510447
1,2.254383e-06,0.705441,0.511854,0.034134,5.032969,152.387746,5.045020,154.247369,0.239437,1.220323
2,3.135050e-06,0.348233,0.460954,0.283262,4.168857,63.641536,4.144576,62.090847,-0.582449,-2.436600
3,3.604113e-06,0.659904,0.123490,0.852356,5.413599,223.437810,5.399942,220.393467,-0.252275,-1.362501
4,3.774481e-06,0.547915,0.649524,0.693039,5.148154,171.113443,5.128244,167.720558,-0.386740,-1.982828
...,...,...,...,...,...,...,...,...,...,...
499707,3.458530e-01,0.084713,0.169534,0.451104,-4.115073,-60.256685,-4.112973,-60.128185,-0.051030,-0.213255
499708,3.460583e-01,0.315792,0.713225,0.709775,-2.779589,-15.112394,-2.777749,-15.082775,-0.066196,-0.195992
499709,3.465390e-01,0.609794,0.212700,0.336352,-2.043512,-6.717664,-2.033212,-6.638579,-0.504036,-1.177258
499710,3.465490e-01,0.432198,0.130247,0.729713,-2.497521,-11.152331,-2.464341,-10.755735,-1.328509,-3.556170
499711,3.466968e-01,0.905265,0.010425,0.778511,-2.397366,-9.994180,-2.397969,-10.000812,0.025154,0.066358

In [69]:
y_pred

array([[-5.08977619],
       [ 5.04501978],
       [ 4.1445757 ],
       ...,
       [-2.03321163],
       [-2.4643412 ],
       [-2.39796909]])

In [70]:
test

NameError: name 'test' is not defined

In [48]:
model, test_data = regressor, test_loader

In [49]:
regressor.train(False)

skip_light(
  (input): Linear(in_features=4, out_features=31, bias=True)
  (act): LeakyReLU(negative_slope=0.01)
  (skip_core): Sequential(
    (0): skip_light_module(
      (act): LeakyReLU(negative_slope=0.01)
      (fc_module): ModuleList(
        (0-4): 5 x Linear(in_features=31, out_features=31, bias=True)
      )
    )
    (1): skip_light_module(
      (act): LeakyReLU(negative_slope=0.01)
      (fc_module): ModuleList(
        (0-4): 5 x Linear(in_features=31, out_features=31, bias=True)
      )
    )
    (2): skip_light_module(
      (act): LeakyReLU(negative_slope=0.01)
      (fc_module): ModuleList(
        (0-4): 5 x Linear(in_features=31, out_features=31, bias=True)
      )
    )
    (3): skip_light_module(
      (act): LeakyReLU(negative_slope=0.01)
      (fc_module): ModuleList(
        (0-4): 5 x Linear(in_features=31, out_features=31, bias=True)
      )
    )
    (4): skip_light_module(
      (act): LeakyReLU(negative_slope=0.01)
      (fc_module): ModuleList(
        (0-4): 5 x Linear(in_features=31, out_features=31, bias=True)
      )
    )
    (5): skip_light_module(
      (act): LeakyReLU(negative_slope=0.01)
      (fc_module): ModuleList(
        (0-4): 5 x Linear(in_features=31, out_features=31, bias=True)
      )
    )
    (6): skip_light_module(
      (act): LeakyReLU(negative_slope=0.01)
      (fc_module): ModuleList(
        (0-4): 5 x Linear(in_features=31, out_features=31, bias=True)
      )
    )
    (7): skip_light_module(
      (act): LeakyReLU(negative_slope=0.01)
      (fc_module): ModuleList(
        (0-4): 5 x Linear(in_features=31, out_features=31, bias=True)
      )
    )
    (8): skip_light_module(
      (act): LeakyReLU(negative_slope=0.01)
      (fc_module): ModuleList(
        (0-4): 5 x Linear(in_features=31, out_features=31, bias=True)
      )
    )
    (9): skip_light_module(
      (act): LeakyReLU(negative_slope=0.01)
      (fc_module): ModuleList(
        (0-4): 5 x Linear(in_features=31, out_features=31, bias=True)
      )
    )
  )
  (output): Linear(in_features=31, out_features=2, bias=True)
)

In [181]:
for i, data in enumerate(test_data):
    # forward prop
    x, y = data
    y_p = model(x)
    
    # store data
    if i == 0:
        x_test = x.cpu().detach().numpy()
        y_test = y.cpu().detach().numpy()
        y_pred = y_p.cpu().detach().numpy()
    else: 
        x_test = np.vstack((x_test, x.cpu().detach().numpy()))
        y_test = np.vstack((y_test, y.cpu().detach().numpy()))
        y_pred = np.vstack((y_pred, y_p.cpu().detach().numpy()))

In [197]:
(1 - np.mean(np.abs((y_unscaler(y_pred) - y_unscaler(y_test))/y_unscaler(y_test))))*100

93.8972764152744

In [186]:
y_pred

array([[-5.15054851,  5.22246609],
       [ 5.00127931, -5.06639124],
       [ 4.16731525, -4.17138413],
       ...,
       [-2.02787016, -1.29885781],
       [-2.50983625, -1.50882085],
       [-2.41709313, -2.52511211]])

In [189]:
def y_unscaler(y):
    ''' function for scaling x1
        argument:
            y: the input variable
        returns:
            the scaled variable
    '''
    y = np.array(y)  # Ensure input is a NumPy array
    return np.where(y >= 0, np.exp(y) - 1, 1 - np.exp(-y))

In [190]:
y_unscaler(y_pred)

array([[-171.52609724,  184.39081056],
       [ 147.60314683, -157.60094054],
       [  63.54194063,  -63.80508853],
       ...,
       [  -6.59788685,   -2.66510802],
       [ -11.30291523,   -3.52139624],
       [ -10.21321656,  -11.49229566]])

In [185]:
y_unscale(y_pred.values)

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [90]:
y_test

array([[-5.16738797,  5.23624844],
       [ 5.03296901, -5.0693969 ],
       [ 4.16885718, -4.18429983],
       ...,
       [-2.04351166, -1.28735805],
       [-2.49752098, -1.4918922 ],
       [-2.39736605, -2.49740627]])

In [106]:
a = 0.1
b = 0.000001
np.abs(a-b)/a

0.99999

In [85]:
# accuracy
y_test = np.array(y_test).reshape(-1, config['n_targets'])
y_pred = np.array(y_pred).reshape(-1, config['n_targets'])
abs_score = (1 - np.mean(np.abs((y_pred - y_test)/y_test)))*100
r2_score = metrics.r2_score(y_test, y_pred)*100

In [82]:
np.abs((y_pred - y_test)/y_test)

array([[0.0032588 , 0.0026321 ],
       [0.00629642, 0.0005929 ],
       [0.00036987, 0.00308671],
       ...,
       [0.00765423, 0.00893284],
       [0.00493099, 0.0113471 ],
       [0.00822865, 0.01109385]])

In [83]:
y_pred

array([[-5.15054851,  5.22246609],
       [ 5.00127931, -5.06639124],
       [ 4.16731525, -4.17138413],
       ...,
       [-2.02787016, -1.29885781],
       [-2.50983625, -1.50882085],
       [-2.41709313, -2.52511211]])

In [115]:
# save test results
df_pred = pd.DataFrame(x_test, columns=['x'+str(i+1) for i in range(config['input_shape'])])

In [116]:
df_pred

                  x1        x2        x3        x4
0       5.434361e-07  0.147431  0.774351  0.245984
1       2.254383e-06  0.705441  0.511854  0.034134
2       3.135050e-06  0.348233  0.460954  0.283262
3       3.604113e-06  0.659904  0.123490  0.852356
4       3.774481e-06  0.547915  0.649524  0.693039
...              ...       ...       ...       ...
499707  3.458530e-01  0.084713  0.169534  0.451104
499708  3.460583e-01  0.315792  0.713225  0.709775
499709  3.465390e-01  0.609794  0.212700  0.336352
499710  3.465490e-01  0.432198  0.130247  0.729713
499711  3.466968e-01  0.905265  0.010425  0.778511

[499712 rows x 4 columns]

In [117]:
# unscale the target
scaled_cname = [s + '_scaled' for s in config['var_y']]
df_pred = pd.concat([df_pred, pd.DataFrame(y_test, columns=scaled_cname)], axis=1)

In [118]:
df_pred

                  x1        x2        x3        x4  y5_scaled  y6_scaled
0       5.434361e-07  0.147431  0.774351  0.245984  -5.167388   5.236248
1       2.254383e-06  0.705441  0.511854  0.034134   5.032969  -5.069397
2       3.135050e-06  0.348233  0.460954  0.283262   4.168857  -4.184300
3       3.604113e-06  0.659904  0.123490  0.852356   5.413599  -5.481205
4       3.774481e-06  0.547915  0.649524  0.693039   5.148154  -5.184982
...              ...       ...       ...       ...        ...        ...
499707  3.458530e-01  0.084713  0.169534  0.451104  -4.115073   0.524211
499708  3.460583e-01  0.315792  0.713225  0.709775  -2.779589  -1.419106
499709  3.465390e-01  0.609794  0.212700  0.336352  -2.043512  -1.287358
499710  3.465490e-01  0.432198  0.130247  0.729713  -2.497521  -1.491892
499711  3.466968e-01  0.905265  0.010425  0.778511  -2.397366  -2.497406

[499712 rows x 6 columns]

In [122]:
for col in df_pred.columns[4:]:
    df_pred[col[:-7]] = df_pred[col].apply(lambda y: y_unscale(y))

In [126]:
df_pred

,x1,x2,x3,x4,y5_scaled,y6_scaled,y5,y6
0,5.434361e-07,0.147431,0.774351,0.245984,-5.167388,5.236248,-174.455943,186.963621
1,2.254383e-06,0.705441,0.511854,0.034134,5.032969,-5.069397,152.387746,-158.078358
2,3.135050e-06,0.348233,0.460954,0.283262,4.168857,-4.184300,63.641536,-64.647520
3,3.604113e-06,0.659904,0.123490,0.852356,5.413599,-5.481205,223.437810,-239.135900
4,3.774481e-06,0.547915,0.649524,0.693039,5.148154,-5.184982,171.113443,-177.570199
...,...,...,...,...,...,...,...,...
499707,3.458530e-01,0.084713,0.169534,0.451104,-4.115073,0.524211,-60.256685,0.689126
499708,3.460583e-01,0.315792,0.713225,0.709775,-2.779589,-1.419106,-15.112394,-3.133422
499709,3.465390e-01,0.609794,0.212700,0.336352,-2.043512,-1.287358,-6.717664,-2.623202
499710,3.465490e-01,0.432198,0.130247,0.729713,-2.497521,-1.491892,-11.152331,-3.445499
499711,3.466968e-01,0.905265,0.010425,0.778511,-2.397366,-2.497406,-9.994180,-11.150937

In [134]:
# y_test_real = pd.DataFrame(np.vectorize(y_unscale)(y_test), columns=config['var_y']) # 
# df_pred = pd.concat([df_pred, y_test_real], axis=1)
y_test_real = df_pred.iloc[:,-config['n_targets']:].to_numpy()

# stuff in the scaled predictions
pred_cname = [s + '_scaled_pred' for s in config['var_y']]
df_pred = pd.concat([df_pred, pd.DataFrame(y_pred, columns=pred_cname)], axis=1)

# stuff in the unscaled predictions
pred_cname = [s + '_pred' for s in config['var_y']]
for col in df_pred.columns[-config['n_targets']:]:
    df_pred[col[:-12]+'_pred'] = df_pred[col].apply(lambda y: y_unscale(y))
# y_pred_real = pd.DataFrame(np.vectorize(y_unscale)(y_pred), columns=pred_cname) # .apply(lambda y: y_unscale(y))
# df_pred = pd.concat([df_pred, y_pred_real], axis=1)
y_pred_real = df_pred.iloc[:,-config['n_targets']:].to_numpy()

# calculate the deltas for the scaled and unscaled targets
scaled_delta_cname = ['scaled_delta_' + s for s in config['var_y']]
df_pred = pd.concat([df_pred, pd.DataFrame((y_pred - y_test)/y_test*100, columns=scaled_delta_cname)], axis=1)
delta_cname = ['delta_' + s for s in config['var_y']]
df_pred = pd.concat([df_pred, pd.DataFrame((y_pred_real - y_test_real)/y_test_real*100, columns=delta_cname)], axis=1)

In [207]:
y_pred_real

array([[-171.52609724,  184.39081056],
       [ 147.60314683, -157.60094054],
       [  63.54194063,  -63.80508853],
       ...,
       [  -6.59788685,   -2.66510802],
       [ -11.30291523,   -3.52139624],
       [ -10.21321656,  -11.49229566]])

In [208]:
y_test_real

array([[-174.45594286,  186.96362132],
       [ 152.38774629, -158.07835759],
       [  63.64153637,  -64.64752027],
       ...,
       [  -6.71766351,   -2.62320157],
       [ -11.15233077,   -3.44549933],
       [  -9.99418008,  -11.15093677]])

In [225]:
(1 - np.mean(np.abs((y_pred_real - y_test_real)/y_test_real)))*100

93.8972764152744

In [226]:
deltas = (y_pred_real - y_test_real)/y_test_real*100
deltas

array([[-1.67941864, -1.37610233],
       [-3.13975341, -0.30201291],
       [-0.15649488, -1.30311533],
       ...,
       [-1.78301077,  1.59753055],
       [ 1.35025102,  2.20278397],
       [ 2.19164033,  3.06125756]])

In [223]:
100 - np.abs(df_pred.iloc[:,i + 4 * num_vars].mean())

99.65569012719484

In [224]:
df_pred.iloc[:,i + 4 * num_vars]

0         -1.376102
1         -0.302013
2         -1.303115
3          0.361828
4          1.120664
            ...
499707   -14.290330
499708    -1.085019
499709     1.597531
499710     2.202784
499711     3.061258
Name: delta_y6, Length: 499712, dtype: float64

In [237]:
100 - np.abs((np.mean(deltas)))

99.90727647574951

In [231]:
(deltas[:, 1])

array([-1.37610233, -0.30201291, -1.30311533, ...,  1.59753055,
        2.20278397,  3.06125756])

In [210]:
y_pred

array([[-5.15054851,  5.22246609],
       [ 5.00127931, -5.06639124],
       [ 4.16731525, -4.17138413],
       ...,
       [-2.02787016, -1.29885781],
       [-2.50983625, -1.50882085],
       [-2.41709313, -2.52511211]])

In [ ]:
(y_pred_real - y_test_real)/y_test_real*100

In [213]:
y_test_real

array([[-174.45594286,  186.96362132],
       [ 152.38774629, -158.07835759],
       [  63.64153637,  -64.64752027],
       ...,
       [  -6.71766351,   -2.62320157],
       [ -11.15233077,   -3.44549933],
       [  -9.99418008,  -11.15093677]])

In [158]:
df_pred

,x1,x2,x3,x4,y5_scaled,y6_scaled,y5,y6,y5_scaled_pred,y6_scaled_pred,y5_pred,y6_pred,scaled_delta_y5,scaled_delta_y6,delta_y5,delta_y6
0,5.434361e-07,0.147431,0.774351,0.245984,-5.167388,5.236248,-174.455943,186.963621,-5.150549,5.222466,-171.526097,184.390811,-0.325880,-0.263210,-1.679419,-1.376102
1,2.254383e-06,0.705441,0.511854,0.034134,5.032969,-5.069397,152.387746,-158.078358,5.001279,-5.066391,147.603147,-157.600941,-0.629642,-0.059290,-3.139753,-0.302013
2,3.135050e-06,0.348233,0.460954,0.283262,4.168857,-4.184300,63.641536,-64.647520,4.167315,-4.171384,63.541941,-63.805089,-0.036987,-0.308671,-0.156495,-1.303115
3,3.604113e-06,0.659904,0.123490,0.852356,5.413599,-5.481205,223.437810,-239.135900,5.367740,-5.484802,213.377844,-240.001161,-0.847100,0.065619,-4.502356,0.361828
4,3.774481e-06,0.547915,0.649524,0.693039,5.148154,-5.184982,171.113443,-177.570199,5.124916,-5.196064,167.160015,-179.560164,-0.451382,0.213737,-2.310414,1.120664
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499707,3.458530e-01,0.084713,0.169534,0.451104,-4.115073,0.524211,-60.256685,0.689126,-4.090355,0.464141,-58.761115,0.590647,-0.600665,-11.459121,-2.481999,-14.290330
499708,3.460583e-01,0.315792,0.713225,0.709775,-2.779589,-1.419106,-15.112394,-3.133422,-2.804856,-1.410846,-15.524700,-3.099423,0.909036,-0.582001,2.728267,-1.085019
499709,3.465390e-01,0.609794,0.212700,0.336352,-2.043512,-1.287358,-6.717664,-2.623202,-2.027870,-1.298858,-6.597887,-2.665108,-0.765423,0.893284,-1.783011,1.597531
499710,3.465490e-01,0.432198,0.130247,0.729713,-2.497521,-1.491892,-11.152331,-3.445499,-2.509836,-1.508821,-11.302915,-3.521396,0.493099,1.134710,1.350251,2.202784
499711,3.466968e-01,0.905265,0.010425,0.778511,-2.397366,-2.497406,-9.994180,-11.150937,-2.417093,-2.525112,-10.213217,-11.492296,0.822865,1.109385,2.191640,3.061258

In [63]:
import copy
cfg = copy.deepcopy(config)

In [ ]:
# accuracy
y_test = np.array(y_test).reshape(-1, config['n_targets'])
y_pred = np.array(y_pred).reshape(-1, config['n_targets'])
abs_score = (1 - np.mean(np.abs((y_pred - y_test)/y_test)))*100
r2_score = metrics.r2_score(y_test, y_pred)*100

In [166]:
y_pred[:, 0]

array([-5.15054851,  5.00127931,  4.16731525, ..., -2.02787016,
       -2.50983625, -2.41709313])

In [171]:
metrics.r2_score(y_test, y_pred)*100

99.8367708984802

In [169]:
metrics.r2_score(y_test[:, 0], y_pred[:, 0])*100

99.80237053943921

In [170]:
metrics.r2_score(y_test[:, 1], y_pred[:, 1])*100

99.87117125752117

In [180]:
y_pred_real, y_test_real

(array([[-171.52609724,  184.39081056],
        [ 147.60314683, -157.60094054],
        [  63.54194063,  -63.80508853],
        ...,
        [  -6.59788685,   -2.66510802],
        [ -11.30291523,   -3.52139624],
        [ -10.21321656,  -11.49229566]]),
 array([[-174.45594286,  186.96362132],
        [ 152.38774629, -158.07835759],
        [  63.64153637,  -64.64752027],
        ...,
        [  -6.71766351,   -2.62320157],
        [ -11.15233077,   -3.44549933],
        [  -9.99418008,  -11.15093677]]))

In [199]:
cfg['test_metrics'] = {}
cfg['test_metrics']['r2'] = {}
cfg['test_metrics']['abs_score'] = {}
num_vars = len(cfg['var_y'])
base_length = cfg['input_shape'] + num_vars
for i in range(base_length, base_length + num_vars):
    test = df_pred.iloc[:,i].values
    pred = df_pred.iloc[:,i + 2 * num_vars].values
    cfg['test_metrics']['r2'][cfg['var_y'][i - base_length]] = metrics.r2_score(test, pred)*100
    cfg['test_metrics']['abs_score'][cfg['var_y'][i - base_length]] = 100 - np.abs(df_pred.iloc[:,i + 4 * num_vars].mean())

cfg['test_metrics']['r2']['model'] = r2_score
cfg['test_metrics']['abs_score']['model'] = abs_score

In [206]:
df_pred.iloc[:,i + 4 * num_vars]

0         -1.376102
1         -0.302013
2         -1.303115
3          0.361828
4          1.120664
            ...
499707   -14.290330
499708    -1.085019
499709     1.597531
499710     2.202784
499711     3.061258
Name: delta_y6, Length: 499712, dtype: float64

In [202]:
metrics.r2_score(test, pred)*100

41.53556692441735

In [162]:
1-np.abs(df_pred.iloc[:,i + 4 * num_vars].mean())

0.6556901271948501

In [222]:
cfg['test_metrics']

{'r2': {'y5': 59.349493799409636,
  'y6': 41.53556692441735,
  'model': 99.8367708984802},
 'abs_score': {'y5': 99.47024307869387,
  'y6': 99.65569012719484,
  'model': 97.01768156003149}}

In [151]:
df_pred

,x1,x2,x3,x4,y5_scaled,y6_scaled,y5,y6,y5_scaled_pred,y6_scaled_pred,y5_pred,y6_pred,scaled_delta_y5,scaled_delta_y6,delta_y5,delta_y6
0,5.434361e-07,0.147431,0.774351,0.245984,-5.167388,5.236248,-174.455943,186.963621,-5.150549,5.222466,-171.526097,184.390811,-0.325880,-0.263210,-1.679419,-1.376102
1,2.254383e-06,0.705441,0.511854,0.034134,5.032969,-5.069397,152.387746,-158.078358,5.001279,-5.066391,147.603147,-157.600941,-0.629642,-0.059290,-3.139753,-0.302013
2,3.135050e-06,0.348233,0.460954,0.283262,4.168857,-4.184300,63.641536,-64.647520,4.167315,-4.171384,63.541941,-63.805089,-0.036987,-0.308671,-0.156495,-1.303115
3,3.604113e-06,0.659904,0.123490,0.852356,5.413599,-5.481205,223.437810,-239.135900,5.367740,-5.484802,213.377844,-240.001161,-0.847100,0.065619,-4.502356,0.361828
4,3.774481e-06,0.547915,0.649524,0.693039,5.148154,-5.184982,171.113443,-177.570199,5.124916,-5.196064,167.160015,-179.560164,-0.451382,0.213737,-2.310414,1.120664
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499707,3.458530e-01,0.084713,0.169534,0.451104,-4.115073,0.524211,-60.256685,0.689126,-4.090355,0.464141,-58.761115,0.590647,-0.600665,-11.459121,-2.481999,-14.290330
499708,3.460583e-01,0.315792,0.713225,0.709775,-2.779589,-1.419106,-15.112394,-3.133422,-2.804856,-1.410846,-15.524700,-3.099423,0.909036,-0.582001,2.728267,-1.085019
499709,3.465390e-01,0.609794,0.212700,0.336352,-2.043512,-1.287358,-6.717664,-2.623202,-2.027870,-1.298858,-6.597887,-2.665108,-0.765423,0.893284,-1.783011,1.597531
499710,3.465490e-01,0.432198,0.130247,0.729713,-2.497521,-1.491892,-11.152331,-3.445499,-2.509836,-1.508821,-11.302915,-3.521396,0.493099,1.134710,1.350251,2.202784
499711,3.466968e-01,0.905265,0.010425,0.778511,-2.397366,-2.497406,-9.994180,-11.150937,-2.417093,-2.525112,-10.213217,-11.492296,0.822865,1.109385,2.191640,3.061258

In [140]:
for i in range(base_length, base_length + num_vars):
    print(i)

6
7

In [138]:
cfg

{'model_type': 'skip-light',
 'input_shape': 4,
 'amplitude_shape': 36,
 'data_dir': '/scratch/akula.ha/dataset',
 'seed': 42,
 'var_y': ['y5', 'y6'],
 'activation': 'leaky_relu',
 'width': 31,
 'depth': 10,
 'skip_block_layers': 5,
 'beta': 0,
 'alpha': 0,
 'normal_scaled': False,
 'lr_decay_type': 'exp',
 'initial_lr': 0.003,
 'final_lr': 1e-06,
 'decay_steps': 120000,
 'train-sample-size': 10000000,
 'validate-sample-size': 500000,
 'test-sample-size': 500000,
 'use_MC_sample': False,
 'batch_size': 1024,
 'steps_per_epoch': 2400,
 'early_stopping_start_epoch': 50,
 'patience': 50,
 'monitor': 'val_mse',
 'loss': 'mse',
 'gradient_clipping': True,
 'verbose': 1,
 'base_directory': '../models/',
 'epochs': 2000,
 'model-uuid': 'ef8e7636',
 'start_time': '2025-05-07 21:39:40 -0400',
 'device': 'cuda',
 'directory': '../models/skip-light-torch-4D-y5_y6-ef8e7636',
 'train-samples-used': 6,
 'validate-samples-used': 6,
 'test-samples-used': 6,
 'n_targets': 2,
 'scaling': {},
 'trainable_parameters': 49819,
 'non_trainable_parameters': 0,
 'total_parameters': 49819,
 'final_decayed_lr': 4.4758200183300384e-05,
 'final_validation_r2': 99.74279299379268,
 'final_validation_loss': 0.026469253109972397,
 'last_epoch': 182,
 'n_training_epochs': 132,
 'fit_time': '2:05:48',
 'test_metrics': {'r2': {'y5': 59.349493799409636,
   'y6': 41.53556692441735,
   'model': 99.8367708984802},
  'abs_score': {'y5': 99.47024307869387,
   'y6': 99.65569012719484,
   'model': 97.01768156003149}},
 'end_time': '2025-05-07 23:47:09 -0400'}

In [69]:
r2_score = metrics.r2_score(y_test, y_pred)*100
abs_score = (1 - np.mean(np.abs((y_pred - y_test)/y_test)))*100

In [70]:
r2_score, abs_score

(99.8367708984802, 97.01768156003149)

In [71]:
y_test, y_pred

(array([[-5.16738797,  5.23624844],
        [ 5.03296901, -5.0693969 ],
        [ 4.16885718, -4.18429983],
        ...,
        [-2.04351166, -1.28735805],
        [-2.49752098, -1.4918922 ],
        [-2.39736605, -2.49740627]]),
 array([[-5.15054851,  5.22246609],
        [ 5.00127931, -5.06639124],
        [ 4.16731525, -4.17138413],
        ...,
        [-2.02787016, -1.29885781],
        [-2.50983625, -1.50882085],
        [-2.41709313, -2.52511211]]))

In [72]:
metrics.r2_score(y_test, y_pred)

0.998367708984802

In [73]:
df_pred.iloc[:,i + 4 * num_vars]

0         -1.376102
1         -0.302013
2         -1.303115
3          0.361828
4          1.120664
            ...
499707   -14.290330
499708    -1.085019
499709     1.597531
499710     2.202784
499711     3.061258
Name: delta_y6, Length: 499712, dtype: float64

In [74]:
100 - np.abs(df_pred.iloc[:,i + 4 * num_vars].mean())

99.65569012719484

In [75]:
test, pred

(array([ 186.96362132, -158.07835759,  -64.64752027, ...,   -2.62320157,
          -3.44549933,  -11.15093677]),
 array([ 184.39081056, -157.60094054,  -63.80508853, ...,   -2.66510802,
          -3.52139624,  -11.49229566]))